; Auto-generated. Do not edit!


(cl:in-package gestos_robot_pkg-msg)


;//! \htmlinclude DiceReadGoal.msg.html

(cl:defclass <DiceReadGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DiceReadGoal (<DiceReadGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DiceReadGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DiceReadGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gestos_robot_pkg-msg:<DiceReadGoal> is deprecated: use gestos_robot_pkg-msg:DiceReadGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DiceReadGoal>) ostream)
  "Serializes a message object of type '<DiceReadGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DiceReadGoal>) istream)
  "Deserializes a message object of type '<DiceReadGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DiceReadGoal>)))
  "Returns string type for a message object of type '<DiceReadGoal>"
  "gestos_robot_pkg/DiceReadGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DiceReadGoal)))
  "Returns string type for a message object of type 'DiceReadGoal"
  "gestos_robot_pkg/DiceReadGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DiceReadGoal>)))
  "Returns md5sum for a message object of type '<DiceReadGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DiceReadGoal)))
  "Returns md5sum for a message object of type 'DiceReadGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DiceReadGoal>)))
  "Returns full string definition for message of type '<DiceReadGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%# No requiere parámetros~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DiceReadGoal)))
  "Returns full string definition for message of type 'DiceReadGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%# No requiere parámetros~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DiceReadGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DiceReadGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DiceReadGoal
))
