; Auto-generated. Do not edit!


(cl:in-package gestos_robot_pkg-msg)


;//! \htmlinclude DiceReadFeedback.msg.html

(cl:defclass <DiceReadFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:string
    :initform ""))
)

(cl:defclass DiceReadFeedback (<DiceReadFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DiceReadFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DiceReadFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gestos_robot_pkg-msg:<DiceReadFeedback> is deprecated: use gestos_robot_pkg-msg:DiceReadFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <DiceReadFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gestos_robot_pkg-msg:status-val is deprecated.  Use gestos_robot_pkg-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DiceReadFeedback>) ostream)
  "Serializes a message object of type '<DiceReadFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DiceReadFeedback>) istream)
  "Deserializes a message object of type '<DiceReadFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DiceReadFeedback>)))
  "Returns string type for a message object of type '<DiceReadFeedback>"
  "gestos_robot_pkg/DiceReadFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DiceReadFeedback)))
  "Returns string type for a message object of type 'DiceReadFeedback"
  "gestos_robot_pkg/DiceReadFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DiceReadFeedback>)))
  "Returns md5sum for a message object of type '<DiceReadFeedback>"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DiceReadFeedback)))
  "Returns md5sum for a message object of type 'DiceReadFeedback"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DiceReadFeedback>)))
  "Returns full string definition for message of type '<DiceReadFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback~%string status # información de progreso~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DiceReadFeedback)))
  "Returns full string definition for message of type 'DiceReadFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback~%string status # información de progreso~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DiceReadFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DiceReadFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DiceReadFeedback
    (cl:cons ':status (status msg))
))
