; Auto-generated. Do not edit!


(cl:in-package gestos_robot_pkg-msg)


;//! \htmlinclude DiceReadResult.msg.html

(cl:defclass <DiceReadResult> (roslisp-msg-protocol:ros-message)
  ((value
    :reader value
    :initarg :value
    :type cl:integer
    :initform 0))
)

(cl:defclass DiceReadResult (<DiceReadResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DiceReadResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DiceReadResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gestos_robot_pkg-msg:<DiceReadResult> is deprecated: use gestos_robot_pkg-msg:DiceReadResult instead.")))

(cl:ensure-generic-function 'value-val :lambda-list '(m))
(cl:defmethod value-val ((m <DiceReadResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gestos_robot_pkg-msg:value-val is deprecated.  Use gestos_robot_pkg-msg:value instead.")
  (value m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DiceReadResult>) ostream)
  "Serializes a message object of type '<DiceReadResult>"
  (cl:let* ((signed (cl:slot-value msg 'value)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DiceReadResult>) istream)
  "Deserializes a message object of type '<DiceReadResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'value) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DiceReadResult>)))
  "Returns string type for a message object of type '<DiceReadResult>"
  "gestos_robot_pkg/DiceReadResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DiceReadResult)))
  "Returns string type for a message object of type 'DiceReadResult"
  "gestos_robot_pkg/DiceReadResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DiceReadResult>)))
  "Returns md5sum for a message object of type '<DiceReadResult>"
  "b3087778e93fcd34cc8d65bc54e850d1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DiceReadResult)))
  "Returns md5sum for a message object of type 'DiceReadResult"
  "b3087778e93fcd34cc8d65bc54e850d1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DiceReadResult>)))
  "Returns full string definition for message of type '<DiceReadResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%int32 value   # valor del dado (-1 si no se detecta)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DiceReadResult)))
  "Returns full string definition for message of type 'DiceReadResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%int32 value   # valor del dado (-1 si no se detecta)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DiceReadResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DiceReadResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DiceReadResult
    (cl:cons ':value (value msg))
))
