; Auto-generated. Do not edit!


(cl:in-package gestos_robot_pkg-msg)


;//! \htmlinclude GestoGoal.msg.html

(cl:defclass <GestoGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GestoGoal (<GestoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GestoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GestoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gestos_robot_pkg-msg:<GestoGoal> is deprecated: use gestos_robot_pkg-msg:GestoGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GestoGoal>) ostream)
  "Serializes a message object of type '<GestoGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GestoGoal>) istream)
  "Deserializes a message object of type '<GestoGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GestoGoal>)))
  "Returns string type for a message object of type '<GestoGoal>"
  "gestos_robot_pkg/GestoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GestoGoal)))
  "Returns string type for a message object of type 'GestoGoal"
  "gestos_robot_pkg/GestoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GestoGoal>)))
  "Returns md5sum for a message object of type '<GestoGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GestoGoal)))
  "Returns md5sum for a message object of type 'GestoGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GestoGoal>)))
  "Returns full string definition for message of type '<GestoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GestoGoal)))
  "Returns full string definition for message of type 'GestoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GestoGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GestoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GestoGoal
))
