
(cl:in-package :asdf)

(defsystem "gestos_robot_pkg-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :actionlib_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "DiceReadAction" :depends-on ("_package_DiceReadAction"))
    (:file "_package_DiceReadAction" :depends-on ("_package"))
    (:file "DiceReadActionFeedback" :depends-on ("_package_DiceReadActionFeedback"))
    (:file "_package_DiceReadActionFeedback" :depends-on ("_package"))
    (:file "DiceReadActionGoal" :depends-on ("_package_DiceReadActionGoal"))
    (:file "_package_DiceReadActionGoal" :depends-on ("_package"))
    (:file "DiceReadActionResult" :depends-on ("_package_DiceReadActionResult"))
    (:file "_package_DiceReadActionResult" :depends-on ("_package"))
    (:file "DiceReadFeedback" :depends-on ("_package_DiceReadFeedback"))
    (:file "_package_DiceReadFeedback" :depends-on ("_package"))
    (:file "DiceReadGoal" :depends-on ("_package_DiceReadGoal"))
    (:file "_package_DiceReadGoal" :depends-on ("_package"))
    (:file "DiceReadResult" :depends-on ("_package_DiceReadResult"))
    (:file "_package_DiceReadResult" :depends-on ("_package"))
    (:file "GestoAction" :depends-on ("_package_GestoAction"))
    (:file "_package_GestoAction" :depends-on ("_package"))
    (:file "GestoActionFeedback" :depends-on ("_package_GestoActionFeedback"))
    (:file "_package_GestoActionFeedback" :depends-on ("_package"))
    (:file "GestoActionGoal" :depends-on ("_package_GestoActionGoal"))
    (:file "_package_GestoActionGoal" :depends-on ("_package"))
    (:file "GestoActionResult" :depends-on ("_package_GestoActionResult"))
    (:file "_package_GestoActionResult" :depends-on ("_package"))
    (:file "GestoFeedback" :depends-on ("_package_GestoFeedback"))
    (:file "_package_GestoFeedback" :depends-on ("_package"))
    (:file "GestoGoal" :depends-on ("_package_GestoGoal"))
    (:file "_package_GestoGoal" :depends-on ("_package"))
    (:file "GestoResult" :depends-on ("_package_GestoResult"))
    (:file "_package_GestoResult" :depends-on ("_package"))
    (:file "Gesture" :depends-on ("_package_Gesture"))
    (:file "_package_Gesture" :depends-on ("_package"))
  ))