// Generated by gencpp from file gestos_robot_pkg/DiceReadResult.msg
// DO NOT EDIT!


#ifndef GESTOS_ROBOT_PKG_MESSAGE_DICEREADRESULT_H
#define GESTOS_ROBOT_PKG_MESSAGE_DICEREADRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gestos_robot_pkg
{
template <class ContainerAllocator>
struct DiceReadResult_
{
  typedef DiceReadResult_<ContainerAllocator> Type;

  DiceReadResult_()
    : value(0)  {
    }
  DiceReadResult_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> const> ConstPtr;

}; // struct DiceReadResult_

typedef ::gestos_robot_pkg::DiceReadResult_<std::allocator<void> > DiceReadResult;

typedef boost::shared_ptr< ::gestos_robot_pkg::DiceReadResult > DiceReadResultPtr;
typedef boost::shared_ptr< ::gestos_robot_pkg::DiceReadResult const> DiceReadResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator1> & lhs, const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator1> & lhs, const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gestos_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3087778e93fcd34ULL;
  static const uint64_t static_value2 = 0xcc8d65bc54e850d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gestos_robot_pkg/DiceReadResult";
  }

  static const char* value(const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Result\n"
"int32 value   # valor del dado (-1 si no se detecta)\n"
;
  }

  static const char* value(const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiceReadResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gestos_robot_pkg::DiceReadResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GESTOS_ROBOT_PKG_MESSAGE_DICEREADRESULT_H
