// Generated by gencpp from file gestos_robot_pkg/GestoGoal.msg
// DO NOT EDIT!


#ifndef GESTOS_ROBOT_PKG_MESSAGE_GESTOGOAL_H
#define GESTOS_ROBOT_PKG_MESSAGE_GESTOGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gestos_robot_pkg
{
template <class ContainerAllocator>
struct GestoGoal_
{
  typedef GestoGoal_<ContainerAllocator> Type;

  GestoGoal_()
    {
    }
  GestoGoal_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GestoGoal_

typedef ::gestos_robot_pkg::GestoGoal_<std::allocator<void> > GestoGoal;

typedef boost::shared_ptr< ::gestos_robot_pkg::GestoGoal > GestoGoalPtr;
typedef boost::shared_ptr< ::gestos_robot_pkg::GestoGoal const> GestoGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gestos_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gestos_robot_pkg::GestoGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gestos_robot_pkg/GestoGoal";
  }

  static const char* value(const ::gestos_robot_pkg::GestoGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
;
  }

  static const char* value(const ::gestos_robot_pkg::GestoGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GestoGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gestos_robot_pkg::GestoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gestos_robot_pkg::GestoGoal_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GESTOS_ROBOT_PKG_MESSAGE_GESTOGOAL_H
