// Generated by gencpp from file gestos_robot_pkg/Gesture.msg
// DO NOT EDIT!


#ifndef GESTOS_ROBOT_PKG_MESSAGE_GESTURE_H
#define GESTOS_ROBOT_PKG_MESSAGE_GESTURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gestos_robot_pkg
{
template <class ContainerAllocator>
struct Gesture_
{
  typedef Gesture_<ContainerAllocator> Type;

  Gesture_()
    : type()
    , source()
    , fingers(0)
    , long_blink(false)  {
    }
  Gesture_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , source(_alloc)
    , fingers(0)
    , long_blink(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_type;
  _source_type source;

   typedef int32_t _fingers_type;
  _fingers_type fingers;

   typedef uint8_t _long_blink_type;
  _long_blink_type long_blink;





  typedef boost::shared_ptr< ::gestos_robot_pkg::Gesture_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gestos_robot_pkg::Gesture_<ContainerAllocator> const> ConstPtr;

}; // struct Gesture_

typedef ::gestos_robot_pkg::Gesture_<std::allocator<void> > Gesture;

typedef boost::shared_ptr< ::gestos_robot_pkg::Gesture > GesturePtr;
typedef boost::shared_ptr< ::gestos_robot_pkg::Gesture const> GestureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gestos_robot_pkg::Gesture_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gestos_robot_pkg::Gesture_<ContainerAllocator1> & lhs, const ::gestos_robot_pkg::Gesture_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.source == rhs.source &&
    lhs.fingers == rhs.fingers &&
    lhs.long_blink == rhs.long_blink;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gestos_robot_pkg::Gesture_<ContainerAllocator1> & lhs, const ::gestos_robot_pkg::Gesture_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gestos_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::Gesture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::Gesture_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::Gesture_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12e6b3f163de8d922be0c5c5e43c1a72";
  }

  static const char* value(const ::gestos_robot_pkg::Gesture_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12e6b3f163de8d92ULL;
  static const uint64_t static_value2 = 0x2be0c5c5e43c1a72ULL;
};

template<class ContainerAllocator>
struct DataType< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gestos_robot_pkg/Gesture";
  }

  static const char* value(const ::gestos_robot_pkg::Gesture_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type       # Nombre del gesto detectado, ej: \"FICHA_ROJA\", \"GUIÑO\"\n"
"string source     # \"mano\" o \"rostro\"\n"
"int32 fingers     # Número de dedos detectados (-1 si no aplica)\n"
"bool long_blink   # Parpadeo largo\n"
;
  }

  static const char* value(const ::gestos_robot_pkg::Gesture_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.source);
      stream.next(m.fingers);
      stream.next(m.long_blink);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gesture_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gestos_robot_pkg::Gesture_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gestos_robot_pkg::Gesture_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fingers: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fingers);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "long_blink: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.long_blink);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GESTOS_ROBOT_PKG_MESSAGE_GESTURE_H
