// Generated by gencpp from file gestos_robot_pkg/GestoFeedback.msg
// DO NOT EDIT!


#ifndef GESTOS_ROBOT_PKG_MESSAGE_GESTOFEEDBACK_H
#define GESTOS_ROBOT_PKG_MESSAGE_GESTOFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gestos_robot_pkg
{
template <class ContainerAllocator>
struct GestoFeedback_
{
  typedef GestoFeedback_<ContainerAllocator> Type;

  GestoFeedback_()
    : status()  {
    }
  GestoFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GestoFeedback_

typedef ::gestos_robot_pkg::GestoFeedback_<std::allocator<void> > GestoFeedback;

typedef boost::shared_ptr< ::gestos_robot_pkg::GestoFeedback > GestoFeedbackPtr;
typedef boost::shared_ptr< ::gestos_robot_pkg::GestoFeedback const> GestoFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator1> & lhs, const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator1> & lhs, const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gestos_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gestos_robot_pkg/GestoFeedback";
  }

  static const char* value(const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Feedback\n"
"string status # información de progreso\n"
"\n"
;
  }

  static const char* value(const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GestoFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gestos_robot_pkg::GestoFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GESTOS_ROBOT_PKG_MESSAGE_GESTOFEEDBACK_H
