// Generated by gencpp from file gestos_robot_pkg/GestoAction.msg
// DO NOT EDIT!


#ifndef GESTOS_ROBOT_PKG_MESSAGE_GESTOACTION_H
#define GESTOS_ROBOT_PKG_MESSAGE_GESTOACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <gestos_robot_pkg/GestoActionGoal.h>
#include <gestos_robot_pkg/GestoActionResult.h>
#include <gestos_robot_pkg/GestoActionFeedback.h>

namespace gestos_robot_pkg
{
template <class ContainerAllocator>
struct GestoAction_
{
  typedef GestoAction_<ContainerAllocator> Type;

  GestoAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  GestoAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::gestos_robot_pkg::GestoActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::gestos_robot_pkg::GestoActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::gestos_robot_pkg::GestoActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> const> ConstPtr;

}; // struct GestoAction_

typedef ::gestos_robot_pkg::GestoAction_<std::allocator<void> > GestoAction;

typedef boost::shared_ptr< ::gestos_robot_pkg::GestoAction > GestoActionPtr;
typedef boost::shared_ptr< ::gestos_robot_pkg::GestoAction const> GestoActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gestos_robot_pkg::GestoAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gestos_robot_pkg::GestoAction_<ContainerAllocator1> & lhs, const ::gestos_robot_pkg::GestoAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gestos_robot_pkg::GestoAction_<ContainerAllocator1> & lhs, const ::gestos_robot_pkg::GestoAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gestos_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a322d5f0e539e3dc090225614f981a48";
  }

  static const char* value(const ::gestos_robot_pkg::GestoAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa322d5f0e539e3dcULL;
  static const uint64_t static_value2 = 0x090225614f981a48ULL;
};

template<class ContainerAllocator>
struct DataType< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gestos_robot_pkg/GestoAction";
  }

  static const char* value(const ::gestos_robot_pkg::GestoAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"GestoActionGoal action_goal\n"
"GestoActionResult action_result\n"
"GestoActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: gestos_robot_pkg/GestoActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"GestoGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: gestos_robot_pkg/GestoGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"\n"
"================================================================================\n"
"MSG: gestos_robot_pkg/GestoActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"GestoResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: gestos_robot_pkg/GestoResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Result\n"
"string type       # Nombre del gesto detectado, ej: \"FICHA_ROJA\", \"GUIÑO\"\n"
"string source     # \"mano\" o \"rostro\"\n"
"int32 fingers     # Número de dedos detectados (-1 si no aplica)\n"
"bool rock         # Gesto rock (🤘)\n"
"bool wink         # Guiño\n"
"\n"
"================================================================================\n"
"MSG: gestos_robot_pkg/GestoActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"GestoFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: gestos_robot_pkg/GestoFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Feedback\n"
"string status # información de progreso\n"
"\n"
;
  }

  static const char* value(const ::gestos_robot_pkg::GestoAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GestoAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gestos_robot_pkg::GestoAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gestos_robot_pkg::GestoAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::gestos_robot_pkg::GestoActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::gestos_robot_pkg::GestoActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::gestos_robot_pkg::GestoActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GESTOS_ROBOT_PKG_MESSAGE_GESTOACTION_H
