# Goal
---

# Result
string type       # Nombre del gesto detectado, ej: "FICHA_ROJA", "GUIÑO"
string source     # "mano" o "rostro"
int32 fingers     # Número de dedos detectados (-1 si no aplica)
bool rock         # Gesto rock (🤘)
bool wink         # Guiño
---

# Feedback
string status # información de progreso
