<?xml version="1.0"?>
<package format="2">

  <name>detector_tablero</name>
  <version>0.1.0</version>
  <description>
    Action server ROS para detección de tablero y fichas con visión por computador,
    devolviendo posiciones en coordenadas reales (cm).
  </description>

  <maintainer email="daniel.kennedy.m1@gmail.com">Daniel Kennedy</maintainer>
  <author email="daniel.kennedy.m1@gmail.com">Daniel Kennedy</author>

  <license>GPL-3.0</license>

  <!-- Build system -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- Build-time dependencies -->
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>actionlib</build_depend>
  <build_depend>actionlib_msgs</build_depend>
  <build_depend>message_generation</build_depend>

  <!-- Run-time dependencies -->
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>actionlib</exec_depend>
  <exec_depend>actionlib_msgs</exec_depend>
  <exec_depend>message_runtime</exec_depend>

  <!-- This package does not export libraries -->
  <export>
  </export>

</package>
