// Auto-generated. Do not edit!

// (in-package detector_tablero.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CasillasGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.modo = null;
    }
    else {
      if (initObj.hasOwnProperty('modo')) {
        this.modo = initObj.modo
      }
      else {
        this.modo = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CasillasGoal
    // Serialize message field [modo]
    bufferOffset = _serializer.uint8(obj.modo, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CasillasGoal
    let len;
    let data = new CasillasGoal(null);
    // Deserialize message field [modo]
    data.modo = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'detector_tablero/CasillasGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'bc4ecbd89e2dc3ed7375583640445dbd';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    uint8 modo #0 tablero y 1 fichas
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CasillasGoal(null);
    if (msg.modo !== undefined) {
      resolved.modo = msg.modo;
    }
    else {
      resolved.modo = 0
    }

    return resolved;
    }
};

module.exports = CasillasGoal;
