// Auto-generated. Do not edit!

// (in-package detector_tablero.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Cell = require('./Cell.js');

//-----------------------------------------------------------

class CasillasResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.casillas = null;
    }
    else {
      if (initObj.hasOwnProperty('casillas')) {
        this.casillas = initObj.casillas
      }
      else {
        this.casillas = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CasillasResult
    // Serialize message field [casillas]
    // Serialize the length for message field [casillas]
    bufferOffset = _serializer.uint32(obj.casillas.length, buffer, bufferOffset);
    obj.casillas.forEach((val) => {
      bufferOffset = Cell.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CasillasResult
    let len;
    let data = new CasillasResult(null);
    // Deserialize message field [casillas]
    // Deserialize array length for message field [casillas]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.casillas = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.casillas[i] = Cell.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    object.casillas.forEach((val) => {
      length += Cell.getMessageSize(val);
    });
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'detector_tablero/CasillasResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4531f2ed2bafe22df2a2808861003ac8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Result
    #Tablero[] casillas
    Cell[] casillas
    
    ================================================================================
    MSG: detector_tablero/Cell
    string label
    geometry_msgs/Pose pose
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CasillasResult(null);
    if (msg.casillas !== undefined) {
      resolved.casillas = new Array(msg.casillas.length);
      for (let i = 0; i < resolved.casillas.length; ++i) {
        resolved.casillas[i] = Cell.Resolve(msg.casillas[i]);
      }
    }
    else {
      resolved.casillas = []
    }

    return resolved;
    }
};

module.exports = CasillasResult;
