// Auto-generated. Do not edit!

// (in-package gestos_robot_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GestoResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.type = null;
      this.source = null;
      this.fingers = null;
      this.rock = null;
      this.wink = null;
    }
    else {
      if (initObj.hasOwnProperty('type')) {
        this.type = initObj.type
      }
      else {
        this.type = '';
      }
      if (initObj.hasOwnProperty('source')) {
        this.source = initObj.source
      }
      else {
        this.source = '';
      }
      if (initObj.hasOwnProperty('fingers')) {
        this.fingers = initObj.fingers
      }
      else {
        this.fingers = 0;
      }
      if (initObj.hasOwnProperty('rock')) {
        this.rock = initObj.rock
      }
      else {
        this.rock = false;
      }
      if (initObj.hasOwnProperty('wink')) {
        this.wink = initObj.wink
      }
      else {
        this.wink = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GestoResult
    // Serialize message field [type]
    bufferOffset = _serializer.string(obj.type, buffer, bufferOffset);
    // Serialize message field [source]
    bufferOffset = _serializer.string(obj.source, buffer, bufferOffset);
    // Serialize message field [fingers]
    bufferOffset = _serializer.int32(obj.fingers, buffer, bufferOffset);
    // Serialize message field [rock]
    bufferOffset = _serializer.bool(obj.rock, buffer, bufferOffset);
    // Serialize message field [wink]
    bufferOffset = _serializer.bool(obj.wink, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GestoResult
    let len;
    let data = new GestoResult(null);
    // Deserialize message field [type]
    data.type = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [source]
    data.source = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [fingers]
    data.fingers = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [rock]
    data.rock = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [wink]
    data.wink = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.type);
    length += _getByteLength(object.source);
    return length + 14;
  }

  static datatype() {
    // Returns string type for a message object
    return 'gestos_robot_pkg/GestoResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6fccb3d0fa481c3a1e9649a7effb88e9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Result
    string type       # Nombre del gesto detectado, ej: "FICHA_ROJA", "GUIÑO"
    string source     # "mano" o "rostro"
    int32 fingers     # Número de dedos detectados (-1 si no aplica)
    bool rock         # Gesto rock (🤘)
    bool wink         # Guiño
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GestoResult(null);
    if (msg.type !== undefined) {
      resolved.type = msg.type;
    }
    else {
      resolved.type = ''
    }

    if (msg.source !== undefined) {
      resolved.source = msg.source;
    }
    else {
      resolved.source = ''
    }

    if (msg.fingers !== undefined) {
      resolved.fingers = msg.fingers;
    }
    else {
      resolved.fingers = 0
    }

    if (msg.rock !== undefined) {
      resolved.rock = msg.rock;
    }
    else {
      resolved.rock = false
    }

    if (msg.wink !== undefined) {
      resolved.wink = msg.wink;
    }
    else {
      resolved.wink = false
    }

    return resolved;
    }
};

module.exports = GestoResult;
