// Generated by gencpp from file detector_tablero/CasillasGoal.msg
// DO NOT EDIT!


#ifndef DETECTOR_TABLERO_MESSAGE_CASILLASGOAL_H
#define DETECTOR_TABLERO_MESSAGE_CASILLASGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detector_tablero
{
template <class ContainerAllocator>
struct CasillasGoal_
{
  typedef CasillasGoal_<ContainerAllocator> Type;

  CasillasGoal_()
    {
    }
  CasillasGoal_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::detector_tablero::CasillasGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_tablero::CasillasGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CasillasGoal_

typedef ::detector_tablero::CasillasGoal_<std::allocator<void> > CasillasGoal;

typedef boost::shared_ptr< ::detector_tablero::CasillasGoal > CasillasGoalPtr;
typedef boost::shared_ptr< ::detector_tablero::CasillasGoal const> CasillasGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_tablero::CasillasGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_tablero::CasillasGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace detector_tablero

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::CasillasGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::CasillasGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::CasillasGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::CasillasGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::CasillasGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::CasillasGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_tablero::CasillasGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::detector_tablero::CasillasGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_tablero::CasillasGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_tablero/CasillasGoal";
  }

  static const char* value(const ::detector_tablero::CasillasGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_tablero::CasillasGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
;
  }

  static const char* value(const ::detector_tablero::CasillasGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_tablero::CasillasGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CasillasGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_tablero::CasillasGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::detector_tablero::CasillasGoal_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_TABLERO_MESSAGE_CASILLASGOAL_H
