// Generated by gencpp from file detector_tablero/CasillasActionGoal.msg
// DO NOT EDIT!


#ifndef DETECTOR_TABLERO_MESSAGE_CASILLASACTIONGOAL_H
#define DETECTOR_TABLERO_MESSAGE_CASILLASACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <detector_tablero/CasillasGoal.h>

namespace detector_tablero
{
template <class ContainerAllocator>
struct CasillasActionGoal_
{
  typedef CasillasActionGoal_<ContainerAllocator> Type;

  CasillasActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  CasillasActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::detector_tablero::CasillasGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CasillasActionGoal_

typedef ::detector_tablero::CasillasActionGoal_<std::allocator<void> > CasillasActionGoal;

typedef boost::shared_ptr< ::detector_tablero::CasillasActionGoal > CasillasActionGoalPtr;
typedef boost::shared_ptr< ::detector_tablero::CasillasActionGoal const> CasillasActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_tablero::CasillasActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detector_tablero::CasillasActionGoal_<ContainerAllocator1> & lhs, const ::detector_tablero::CasillasActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detector_tablero::CasillasActionGoal_<ContainerAllocator1> & lhs, const ::detector_tablero::CasillasActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detector_tablero

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9b9e6797c12b711b561fb4ad763c9a4";
  }

  static const char* value(const ::detector_tablero::CasillasActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9b9e6797c12b711ULL;
  static const uint64_t static_value2 = 0xb561fb4ad763c9a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_tablero/CasillasActionGoal";
  }

  static const char* value(const ::detector_tablero::CasillasActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CasillasGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: detector_tablero/CasillasGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"uint8 modo #0 tablero y 1 fichas\n"
;
  }

  static const char* value(const ::detector_tablero::CasillasActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CasillasActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_tablero::CasillasActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detector_tablero::CasillasActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::detector_tablero::CasillasGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_TABLERO_MESSAGE_CASILLASACTIONGOAL_H
