// Generated by gencpp from file detector_tablero/CasillasFeedback.msg
// DO NOT EDIT!


#ifndef DETECTOR_TABLERO_MESSAGE_CASILLASFEEDBACK_H
#define DETECTOR_TABLERO_MESSAGE_CASILLASFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detector_tablero
{
template <class ContainerAllocator>
struct CasillasFeedback_
{
  typedef CasillasFeedback_<ContainerAllocator> Type;

  CasillasFeedback_()
    : detected_count(0)  {
    }
  CasillasFeedback_(const ContainerAllocator& _alloc)
    : detected_count(0)  {
  (void)_alloc;
    }



   typedef int32_t _detected_count_type;
  _detected_count_type detected_count;





  typedef boost::shared_ptr< ::detector_tablero::CasillasFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_tablero::CasillasFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CasillasFeedback_

typedef ::detector_tablero::CasillasFeedback_<std::allocator<void> > CasillasFeedback;

typedef boost::shared_ptr< ::detector_tablero::CasillasFeedback > CasillasFeedbackPtr;
typedef boost::shared_ptr< ::detector_tablero::CasillasFeedback const> CasillasFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_tablero::CasillasFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detector_tablero::CasillasFeedback_<ContainerAllocator1> & lhs, const ::detector_tablero::CasillasFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.detected_count == rhs.detected_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detector_tablero::CasillasFeedback_<ContainerAllocator1> & lhs, const ::detector_tablero::CasillasFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detector_tablero

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::CasillasFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::CasillasFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::CasillasFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "740279718b6c5ba60e53258664360094";
  }

  static const char* value(const ::detector_tablero::CasillasFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x740279718b6c5ba6ULL;
  static const uint64_t static_value2 = 0x0e53258664360094ULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_tablero/CasillasFeedback";
  }

  static const char* value(const ::detector_tablero::CasillasFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Feedback\n"
"int32 detected_count\n"
"\n"
;
  }

  static const char* value(const ::detector_tablero::CasillasFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detected_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CasillasFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_tablero::CasillasFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detector_tablero::CasillasFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "detected_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.detected_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_TABLERO_MESSAGE_CASILLASFEEDBACK_H
