// Generated by gencpp from file detector_tablero/CasillasResult.msg
// DO NOT EDIT!


#ifndef DETECTOR_TABLERO_MESSAGE_CASILLASRESULT_H
#define DETECTOR_TABLERO_MESSAGE_CASILLASRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <detector_tablero/Cell.h>
#include <detector_tablero/Ficha.h>

namespace detector_tablero
{
template <class ContainerAllocator>
struct CasillasResult_
{
  typedef CasillasResult_<ContainerAllocator> Type;

  CasillasResult_()
    : casillas()
    , fichas()  {
    }
  CasillasResult_(const ContainerAllocator& _alloc)
    : casillas(_alloc)
    , fichas(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::detector_tablero::Cell_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::detector_tablero::Cell_<ContainerAllocator> >> _casillas_type;
  _casillas_type casillas;

   typedef std::vector< ::detector_tablero::Ficha_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::detector_tablero::Ficha_<ContainerAllocator> >> _fichas_type;
  _fichas_type fichas;





  typedef boost::shared_ptr< ::detector_tablero::CasillasResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_tablero::CasillasResult_<ContainerAllocator> const> ConstPtr;

}; // struct CasillasResult_

typedef ::detector_tablero::CasillasResult_<std::allocator<void> > CasillasResult;

typedef boost::shared_ptr< ::detector_tablero::CasillasResult > CasillasResultPtr;
typedef boost::shared_ptr< ::detector_tablero::CasillasResult const> CasillasResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_tablero::CasillasResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_tablero::CasillasResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detector_tablero::CasillasResult_<ContainerAllocator1> & lhs, const ::detector_tablero::CasillasResult_<ContainerAllocator2> & rhs)
{
  return lhs.casillas == rhs.casillas &&
    lhs.fichas == rhs.fichas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detector_tablero::CasillasResult_<ContainerAllocator1> & lhs, const ::detector_tablero::CasillasResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detector_tablero

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::CasillasResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::CasillasResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::CasillasResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::CasillasResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::CasillasResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::CasillasResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_tablero::CasillasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e2d5f6c94520d304531a7e7b2f9f8fd";
  }

  static const char* value(const ::detector_tablero::CasillasResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e2d5f6c94520d30ULL;
  static const uint64_t static_value2 = 0x4531a7e7b2f9f8fdULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_tablero::CasillasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_tablero/CasillasResult";
  }

  static const char* value(const ::detector_tablero::CasillasResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_tablero::CasillasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Result\n"
"Cell[] casillas\n"
"Ficha[] fichas\n"
"\n"
"================================================================================\n"
"MSG: detector_tablero/Cell\n"
"uint8 idx\n"
"string color\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: detector_tablero/Ficha\n"
"string color\n"
"int32 idx\n"
"geometry_msgs/Pose pose\n"
;
  }

  static const char* value(const ::detector_tablero::CasillasResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_tablero::CasillasResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.casillas);
      stream.next(m.fichas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CasillasResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_tablero::CasillasResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detector_tablero::CasillasResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "casillas: ";
    if (v.casillas.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.casillas.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::detector_tablero::Cell_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.casillas[i]);
    }
    if (v.casillas.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fichas: ";
    if (v.fichas.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.fichas.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::detector_tablero::Ficha_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.fichas[i]);
    }
    if (v.fichas.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_TABLERO_MESSAGE_CASILLASRESULT_H
