// Generated by gencpp from file detector_tablero/Cell.msg
// DO NOT EDIT!


#ifndef DETECTOR_TABLERO_MESSAGE_CELL_H
#define DETECTOR_TABLERO_MESSAGE_CELL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace detector_tablero
{
template <class ContainerAllocator>
struct Cell_
{
  typedef Cell_<ContainerAllocator> Type;

  Cell_()
    : idx()
    , color()
    , pose()  {
    }
  Cell_(const ContainerAllocator& _alloc)
    : idx(_alloc)
    , color(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _idx_type;
  _idx_type idx;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::detector_tablero::Cell_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_tablero::Cell_<ContainerAllocator> const> ConstPtr;

}; // struct Cell_

typedef ::detector_tablero::Cell_<std::allocator<void> > Cell;

typedef boost::shared_ptr< ::detector_tablero::Cell > CellPtr;
typedef boost::shared_ptr< ::detector_tablero::Cell const> CellConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_tablero::Cell_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_tablero::Cell_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detector_tablero::Cell_<ContainerAllocator1> & lhs, const ::detector_tablero::Cell_<ContainerAllocator2> & rhs)
{
  return lhs.idx == rhs.idx &&
    lhs.color == rhs.color &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detector_tablero::Cell_<ContainerAllocator1> & lhs, const ::detector_tablero::Cell_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detector_tablero

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::Cell_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::Cell_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::Cell_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::Cell_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::Cell_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::Cell_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_tablero::Cell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ff0b5688a4dc590464614af933c2f7d";
  }

  static const char* value(const ::detector_tablero::Cell_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ff0b5688a4dc590ULL;
  static const uint64_t static_value2 = 0x464614af933c2f7dULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_tablero::Cell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_tablero/Cell";
  }

  static const char* value(const ::detector_tablero::Cell_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_tablero::Cell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string idx\n"
"string color\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::detector_tablero::Cell_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_tablero::Cell_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx);
      stream.next(m.color);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cell_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_tablero::Cell_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detector_tablero::Cell_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "idx: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.idx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_TABLERO_MESSAGE_CELL_H
