// Generated by gencpp from file detector_tablero/Tablero.msg
// DO NOT EDIT!


#ifndef DETECTOR_TABLERO_MESSAGE_TABLERO_H
#define DETECTOR_TABLERO_MESSAGE_TABLERO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace detector_tablero
{
template <class ContainerAllocator>
struct Tablero_
{
  typedef Tablero_<ContainerAllocator> Type;

  Tablero_()
    : colores()
    , casillas()  {
    }
  Tablero_(const ContainerAllocator& _alloc)
    : colores(_alloc)
    , casillas(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _colores_type;
  _colores_type colores;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _casillas_type;
  _casillas_type casillas;





  typedef boost::shared_ptr< ::detector_tablero::Tablero_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_tablero::Tablero_<ContainerAllocator> const> ConstPtr;

}; // struct Tablero_

typedef ::detector_tablero::Tablero_<std::allocator<void> > Tablero;

typedef boost::shared_ptr< ::detector_tablero::Tablero > TableroPtr;
typedef boost::shared_ptr< ::detector_tablero::Tablero const> TableroConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_tablero::Tablero_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_tablero::Tablero_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detector_tablero::Tablero_<ContainerAllocator1> & lhs, const ::detector_tablero::Tablero_<ContainerAllocator2> & rhs)
{
  return lhs.colores == rhs.colores &&
    lhs.casillas == rhs.casillas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detector_tablero::Tablero_<ContainerAllocator1> & lhs, const ::detector_tablero::Tablero_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detector_tablero

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::Tablero_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_tablero::Tablero_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::Tablero_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_tablero::Tablero_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::Tablero_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_tablero::Tablero_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_tablero::Tablero_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71151b07a522e59996993ee37495dfc2";
  }

  static const char* value(const ::detector_tablero::Tablero_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71151b07a522e599ULL;
  static const uint64_t static_value2 = 0x96993ee37495dfc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_tablero::Tablero_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_tablero/Tablero";
  }

  static const char* value(const ::detector_tablero::Tablero_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_tablero::Tablero_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] colores\n"
"geometry_msgs/Pose casillas\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::detector_tablero::Tablero_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_tablero::Tablero_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.colores);
      stream.next(m.casillas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tablero_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_tablero::Tablero_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detector_tablero::Tablero_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "colores: ";
    if (v.colores.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.colores.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.colores[i]);
    }
    if (v.colores.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "casillas: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.casillas);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_TABLERO_MESSAGE_TABLERO_H
