(cl:defpackage detector_tablero-msg
  (:use )
  (:export
   "<CASILLASACTION>"
   "CASILLASACTION"
   "<CASILLASACTIONFEEDBACK>"
   "CASILLASACTIONFEEDBACK"
   "<CASILLASACTIONGOAL>"
   "CASILLASACTIONGOAL"
   "<CASILLASACTIONRESULT>"
   "CASILLASACTIONRESULT"
   "<CASILLASFEEDBACK>"
   "CASILLASFEEDBACK"
   "<CASILLASGOAL>"
   "CASILLASGOAL"
   "<CASILLASRESULT>"
   "CASILLASRESULT"
   "<CELL>"
   "CELL"
   "<FICHA>"
   "FICHA"
  ))

