; Auto-generated. Do not edit!


(cl:in-package detector_tablero-msg)


;//! \htmlinclude CasillasGoal.msg.html

(cl:defclass <CasillasGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CasillasGoal (<CasillasGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CasillasGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CasillasGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name detector_tablero-msg:<CasillasGoal> is deprecated: use detector_tablero-msg:CasillasGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CasillasGoal>) ostream)
  "Serializes a message object of type '<CasillasGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CasillasGoal>) istream)
  "Deserializes a message object of type '<CasillasGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CasillasGoal>)))
  "Returns string type for a message object of type '<CasillasGoal>"
  "detector_tablero/CasillasGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CasillasGoal)))
  "Returns string type for a message object of type 'CasillasGoal"
  "detector_tablero/CasillasGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CasillasGoal>)))
  "Returns md5sum for a message object of type '<CasillasGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CasillasGoal)))
  "Returns md5sum for a message object of type 'CasillasGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CasillasGoal>)))
  "Returns full string definition for message of type '<CasillasGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CasillasGoal)))
  "Returns full string definition for message of type 'CasillasGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CasillasGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CasillasGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CasillasGoal
))
