; Auto-generated. Do not edit!


(cl:in-package detector_tablero-msg)


;//! \htmlinclude CasillasGoal.msg.html

(cl:defclass <CasillasGoal> (roslisp-msg-protocol:ros-message)
  ((modo
    :reader modo
    :initarg :modo
    :type cl:fixnum
    :initform 0))
)

(cl:defclass CasillasGoal (<CasillasGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CasillasGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CasillasGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name detector_tablero-msg:<CasillasGoal> is deprecated: use detector_tablero-msg:CasillasGoal instead.")))

(cl:ensure-generic-function 'modo-val :lambda-list '(m))
(cl:defmethod modo-val ((m <CasillasGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader detector_tablero-msg:modo-val is deprecated.  Use detector_tablero-msg:modo instead.")
  (modo m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CasillasGoal>) ostream)
  "Serializes a message object of type '<CasillasGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'modo)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CasillasGoal>) istream)
  "Deserializes a message object of type '<CasillasGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'modo)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CasillasGoal>)))
  "Returns string type for a message object of type '<CasillasGoal>"
  "detector_tablero/CasillasGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CasillasGoal)))
  "Returns string type for a message object of type 'CasillasGoal"
  "detector_tablero/CasillasGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CasillasGoal>)))
  "Returns md5sum for a message object of type '<CasillasGoal>"
  "bc4ecbd89e2dc3ed7375583640445dbd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CasillasGoal)))
  "Returns md5sum for a message object of type 'CasillasGoal"
  "bc4ecbd89e2dc3ed7375583640445dbd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CasillasGoal>)))
  "Returns full string definition for message of type '<CasillasGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%uint8 modo #0 tablero y 1 fichas~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CasillasGoal)))
  "Returns full string definition for message of type 'CasillasGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%uint8 modo #0 tablero y 1 fichas~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CasillasGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CasillasGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CasillasGoal
    (cl:cons ':modo (modo msg))
))
