; Auto-generated. Do not edit!


(cl:in-package detector_tablero-msg)


;//! \htmlinclude CasillasFeedback.msg.html

(cl:defclass <CasillasFeedback> (roslisp-msg-protocol:ros-message)
  ((detected_count
    :reader detected_count
    :initarg :detected_count
    :type cl:integer
    :initform 0))
)

(cl:defclass CasillasFeedback (<CasillasFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CasillasFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CasillasFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name detector_tablero-msg:<CasillasFeedback> is deprecated: use detector_tablero-msg:CasillasFeedback instead.")))

(cl:ensure-generic-function 'detected_count-val :lambda-list '(m))
(cl:defmethod detected_count-val ((m <CasillasFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader detector_tablero-msg:detected_count-val is deprecated.  Use detector_tablero-msg:detected_count instead.")
  (detected_count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CasillasFeedback>) ostream)
  "Serializes a message object of type '<CasillasFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'detected_count)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CasillasFeedback>) istream)
  "Deserializes a message object of type '<CasillasFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'detected_count) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CasillasFeedback>)))
  "Returns string type for a message object of type '<CasillasFeedback>"
  "detector_tablero/CasillasFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CasillasFeedback)))
  "Returns string type for a message object of type 'CasillasFeedback"
  "detector_tablero/CasillasFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CasillasFeedback>)))
  "Returns md5sum for a message object of type '<CasillasFeedback>"
  "740279718b6c5ba60e53258664360094")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CasillasFeedback)))
  "Returns md5sum for a message object of type 'CasillasFeedback"
  "740279718b6c5ba60e53258664360094")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CasillasFeedback>)))
  "Returns full string definition for message of type '<CasillasFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback~%int32 detected_count~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CasillasFeedback)))
  "Returns full string definition for message of type 'CasillasFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback~%int32 detected_count~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CasillasFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CasillasFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CasillasFeedback
    (cl:cons ':detected_count (detected_count msg))
))
