; Auto-generated. Do not edit!


(cl:in-package detector_tablero-msg)


;//! \htmlinclude CasillasResult.msg.html

(cl:defclass <CasillasResult> (roslisp-msg-protocol:ros-message)
  ((casillas
    :reader casillas
    :initarg :casillas
    :type (cl:vector detector_tablero-msg:Cell)
   :initform (cl:make-array 0 :element-type 'detector_tablero-msg:Cell :initial-element (cl:make-instance 'detector_tablero-msg:Cell))))
)

(cl:defclass CasillasResult (<CasillasResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CasillasResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CasillasResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name detector_tablero-msg:<CasillasResult> is deprecated: use detector_tablero-msg:CasillasResult instead.")))

(cl:ensure-generic-function 'casillas-val :lambda-list '(m))
(cl:defmethod casillas-val ((m <CasillasResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader detector_tablero-msg:casillas-val is deprecated.  Use detector_tablero-msg:casillas instead.")
  (casillas m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CasillasResult>) ostream)
  "Serializes a message object of type '<CasillasResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'casillas))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'casillas))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CasillasResult>) istream)
  "Deserializes a message object of type '<CasillasResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'casillas) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'casillas)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'detector_tablero-msg:Cell))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CasillasResult>)))
  "Returns string type for a message object of type '<CasillasResult>"
  "detector_tablero/CasillasResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CasillasResult)))
  "Returns string type for a message object of type 'CasillasResult"
  "detector_tablero/CasillasResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CasillasResult>)))
  "Returns md5sum for a message object of type '<CasillasResult>"
  "889ad1042553438270f2c0c5938aacea")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CasillasResult)))
  "Returns md5sum for a message object of type 'CasillasResult"
  "889ad1042553438270f2c0c5938aacea")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CasillasResult>)))
  "Returns full string definition for message of type '<CasillasResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%#Tablero[] casillas~%Cell[] casillas~%~%================================================================================~%MSG: detector_tablero/Cell~%string idx~%string color~%geometry_msgs/Pose pose~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CasillasResult)))
  "Returns full string definition for message of type 'CasillasResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%#Tablero[] casillas~%Cell[] casillas~%~%================================================================================~%MSG: detector_tablero/Cell~%string idx~%string color~%geometry_msgs/Pose pose~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CasillasResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'casillas) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CasillasResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CasillasResult
    (cl:cons ':casillas (casillas msg))
))
